import xgboost as xgb
from typing import Optional, Protocol, Tuple


class XgboostContextServicePort(Protocol):
    def save_league_model(self, model: xgb.Booster, league_id: str): ...
    def save_league_models(
        self, model_home: xgb.Booster, model_away: xgb.Booster, league_id: str
    ): ...
    def load_league_model(self, league_id: str) -> Optional[xgb.Booster]: ...
    def load_league_models(self, league_id: str) -> Tuple[xgb.Booster, xgb.Booster]: ...
