# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimulationService/SimulationEngine/requests.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSimulationProtos.SimulationService import commonTypes_pb2 as SimulationService_dot_commonTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1SimulationService/SimulationEngine/requests.proto\x12\x31SimPitchProtos.SimulationService.SimulationEngine\x1a#SimulationService/commonTypes.proto\"o\n\x1aRunSimulationEngineRequest\x12Q\n\x11simulation_params\x18\x01 \x01(\x0b\x32\x36.SimPitchProtos.SimulationService.SimulationParamsGrpc\"9\n GetSimulationOverviewByIdRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"6\n\x1dGetSimulationStateByIdRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"-\n\x1dGetLatestSimulationIdsRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\".\n\x15StopSimulationRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\tB4\xaa\x02\x31SimPitchProtos.SimulationService.SimulationEngineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimulationService.SimulationEngine.requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0021SimPitchProtos.SimulationService.SimulationEngine'
  _globals['_RUNSIMULATIONENGINEREQUEST']._serialized_start=141
  _globals['_RUNSIMULATIONENGINEREQUEST']._serialized_end=252
  _globals['_GETSIMULATIONOVERVIEWBYIDREQUEST']._serialized_start=254
  _globals['_GETSIMULATIONOVERVIEWBYIDREQUEST']._serialized_end=311
  _globals['_GETSIMULATIONSTATEBYIDREQUEST']._serialized_start=313
  _globals['_GETSIMULATIONSTATEBYIDREQUEST']._serialized_end=367
  _globals['_GETLATESTSIMULATIONIDSREQUEST']._serialized_start=369
  _globals['_GETLATESTSIMULATIONIDSREQUEST']._serialized_end=414
  _globals['_STOPSIMULATIONREQUEST']._serialized_start=416
  _globals['_STOPSIMULATIONREQUEST']._serialized_end=462
# @@protoc_insertion_point(module_scope)
