# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimulationService/SimulationEngine/responses.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSimulationProtos.SimulationService import commonTypes_pb2 as SimulationService_dot_commonTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2SimulationService/SimulationEngine/responses.proto\x12\x31SimPitchProtos.SimulationService.SimulationEngine\x1a#SimulationService/commonTypes.proto\"4\n\x1bRunSimulationEngineResponse\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\"s\n\x1aSimulationOverviewResponse\x12U\n\x13simulation_overview\x18\x01 \x01(\x0b\x32\x38.SimPitchProtos.SimulationService.SimulationOverviewGrpc\"\xaf\x01\n SimulationOverviewsPagedResponse\x12G\n\x05items\x18\x01 \x03(\x0b\x32\x38.SimPitchProtos.SimulationService.SimulationOverviewGrpc\x12\x42\n\x05paged\x18\x02 \x01(\x0b\x32\x33.SimPitchProtos.SimulationService.PagedResponseGrpc\"j\n\x17SimulationStateResponse\x12O\n\x10simulation_state\x18\x01 \x01(\x0b\x32\x35.SimPitchProtos.SimulationService.SimulationStateGrpc\"/\n\x15SimulationIdsResponse\x12\x16\n\x0esimulation_ids\x18\x01 \x03(\t\"(\n\x16StopSimulationResponse\x12\x0e\n\x06status\x18\x01 \x01(\tB4\xaa\x02\x31SimPitchProtos.SimulationService.SimulationEngineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimulationService.SimulationEngine.responses_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0021SimPitchProtos.SimulationService.SimulationEngine'
  _globals['_RUNSIMULATIONENGINERESPONSE']._serialized_start=142
  _globals['_RUNSIMULATIONENGINERESPONSE']._serialized_end=194
  _globals['_SIMULATIONOVERVIEWRESPONSE']._serialized_start=196
  _globals['_SIMULATIONOVERVIEWRESPONSE']._serialized_end=311
  _globals['_SIMULATIONOVERVIEWSPAGEDRESPONSE']._serialized_start=314
  _globals['_SIMULATIONOVERVIEWSPAGEDRESPONSE']._serialized_end=489
  _globals['_SIMULATIONSTATERESPONSE']._serialized_start=491
  _globals['_SIMULATIONSTATERESPONSE']._serialized_end=597
  _globals['_SIMULATIONIDSRESPONSE']._serialized_start=599
  _globals['_SIMULATIONIDSRESPONSE']._serialized_end=646
  _globals['_STOPSIMULATIONRESPONSE']._serialized_start=648
  _globals['_STOPSIMULATIONRESPONSE']._serialized_end=688
# @@protoc_insertion_point(module_scope)
