# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.generatedSimulationProtos.SimulationService.SimulationEngine import requests_pb2 as SimulationService_dot_SimulationEngine_dot_requests__pb2
from src.generatedSimulationProtos.SimulationService.SimulationEngine import responses_pb2 as SimulationService_dot_SimulationEngine_dot_responses__pb2
from src.generatedSimulationProtos.SimulationService import commonTypes_pb2 as SimulationService_dot_commonTypes__pb2


class SimulationEngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSimulation = channel.unary_unary(
                '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/RunSimulation',
                request_serializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.RunSimulationEngineRequest.SerializeToString,
                response_deserializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.RunSimulationEngineResponse.FromString,
                )
        self.GetSimulationOverviewById = channel.unary_unary(
                '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetSimulationOverviewById',
                request_serializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.GetSimulationOverviewByIdRequest.SerializeToString,
                response_deserializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationOverviewResponse.FromString,
                )
        self.GetAllSimulationOverviews = channel.unary_unary(
                '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetAllSimulationOverviews',
                request_serializer=SimulationService_dot_commonTypes__pb2.PagedRequestGrpc.SerializeToString,
                response_deserializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationOverviewsPagedResponse.FromString,
                )
        self.GetSimulationStateById = channel.unary_unary(
                '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetSimulationStateById',
                request_serializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.GetSimulationStateByIdRequest.SerializeToString,
                response_deserializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationStateResponse.FromString,
                )
        self.GetLatestSimulationIds = channel.unary_unary(
                '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetLatestSimulationIds',
                request_serializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.GetLatestSimulationIdsRequest.SerializeToString,
                response_deserializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationIdsResponse.FromString,
                )
        self.StopSimulationById = channel.unary_unary(
                '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/StopSimulationById',
                request_serializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.StopSimulationRequest.SerializeToString,
                response_deserializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.StopSimulationResponse.FromString,
                )


class SimulationEngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationOverviewById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllSimulationOverviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimulationStateById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestSimulationIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSimulationById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSimulation,
                    request_deserializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.RunSimulationEngineRequest.FromString,
                    response_serializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.RunSimulationEngineResponse.SerializeToString,
            ),
            'GetSimulationOverviewById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationOverviewById,
                    request_deserializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.GetSimulationOverviewByIdRequest.FromString,
                    response_serializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationOverviewResponse.SerializeToString,
            ),
            'GetAllSimulationOverviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSimulationOverviews,
                    request_deserializer=SimulationService_dot_commonTypes__pb2.PagedRequestGrpc.FromString,
                    response_serializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationOverviewsPagedResponse.SerializeToString,
            ),
            'GetSimulationStateById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimulationStateById,
                    request_deserializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.GetSimulationStateByIdRequest.FromString,
                    response_serializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationStateResponse.SerializeToString,
            ),
            'GetLatestSimulationIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestSimulationIds,
                    request_deserializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.GetLatestSimulationIdsRequest.FromString,
                    response_serializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationIdsResponse.SerializeToString,
            ),
            'StopSimulationById': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSimulationById,
                    request_deserializer=SimulationService_dot_SimulationEngine_dot_requests__pb2.StopSimulationRequest.FromString,
                    response_serializer=SimulationService_dot_SimulationEngine_dot_responses__pb2.StopSimulationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulationEngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/RunSimulation',
            SimulationService_dot_SimulationEngine_dot_requests__pb2.RunSimulationEngineRequest.SerializeToString,
            SimulationService_dot_SimulationEngine_dot_responses__pb2.RunSimulationEngineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationOverviewById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetSimulationOverviewById',
            SimulationService_dot_SimulationEngine_dot_requests__pb2.GetSimulationOverviewByIdRequest.SerializeToString,
            SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationOverviewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllSimulationOverviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetAllSimulationOverviews',
            SimulationService_dot_commonTypes__pb2.PagedRequestGrpc.SerializeToString,
            SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationOverviewsPagedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimulationStateById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetSimulationStateById',
            SimulationService_dot_SimulationEngine_dot_requests__pb2.GetSimulationStateByIdRequest.SerializeToString,
            SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestSimulationIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/GetLatestSimulationIds',
            SimulationService_dot_SimulationEngine_dot_requests__pb2.GetLatestSimulationIdsRequest.SerializeToString,
            SimulationService_dot_SimulationEngine_dot_responses__pb2.SimulationIdsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopSimulationById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.SimulationEngine.SimulationEngineService/StopSimulationById',
            SimulationService_dot_SimulationEngine_dot_requests__pb2.StopSimulationRequest.SerializeToString,
            SimulationService_dot_SimulationEngine_dot_responses__pb2.StopSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
