# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SportsDataService/LeagueRound/requests.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,SportsDataService/LeagueRound/requests.proto\x12,SimPitchProtos.SportsDataService.LeagueRound\"\x8c\x01\n\x1bLeagueRoundsByParamsRequest\x12\x11\n\tleague_id\x18\x01 \x01(\t\x12\x18\n\x0bseason_year\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x0fleague_round_id\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_season_yearB\x12\n\x10_league_round_idB/\xaa\x02,SimPitchProtos.SportsDataService.LeagueRoundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SportsDataService.LeagueRound.requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002,SimPitchProtos.SportsDataService.LeagueRound'
  _globals['_LEAGUEROUNDSBYPARAMSREQUEST']._serialized_start=95
  _globals['_LEAGUEROUNDSBYPARAMSREQUEST']._serialized_end=235
# @@protoc_insertion_point(module_scope)
