# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SportsDataService/LeagueRound/responses.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSportsDataProtos.SportsDataService import commonTypes_pb2 as SportsDataService_dot_commonTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-SportsDataService/LeagueRound/responses.proto\x12,SimPitchProtos.SportsDataService.LeagueRound\x1a#SportsDataService/commonTypes.proto\"h\n\x1cLeagueRoundsByParamsResponse\x12H\n\rleague_rounds\x18\x01 \x03(\x0b\x32\x31.SimPitchProtos.SportsDataService.LeagueRoundGrpcB/\xaa\x02,SimPitchProtos.SportsDataService.LeagueRoundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SportsDataService.LeagueRound.responses_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002,SimPitchProtos.SportsDataService.LeagueRound'
  _globals['_LEAGUEROUNDSBYPARAMSRESPONSE']._serialized_start=132
  _globals['_LEAGUEROUNDSBYPARAMSRESPONSE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
