# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.generatedSportsDataProtos.SportsDataService.LeagueRound import requests_pb2 as SportsDataService_dot_LeagueRound_dot_requests__pb2
from src.generatedSportsDataProtos.SportsDataService.LeagueRound import responses_pb2 as SportsDataService_dot_LeagueRound_dot_responses__pb2


class LeagueRoundServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllLeagueRoundsByParams = channel.unary_unary(
                '/SimPitchProtos.SportsDataService.LeagueRound.LeagueRoundService/GetAllLeagueRoundsByParams',
                request_serializer=SportsDataService_dot_LeagueRound_dot_requests__pb2.LeagueRoundsByParamsRequest.SerializeToString,
                response_deserializer=SportsDataService_dot_LeagueRound_dot_responses__pb2.LeagueRoundsByParamsResponse.FromString,
                )


class LeagueRoundServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllLeagueRoundsByParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LeagueRoundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllLeagueRoundsByParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllLeagueRoundsByParams,
                    request_deserializer=SportsDataService_dot_LeagueRound_dot_requests__pb2.LeagueRoundsByParamsRequest.FromString,
                    response_serializer=SportsDataService_dot_LeagueRound_dot_responses__pb2.LeagueRoundsByParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimPitchProtos.SportsDataService.LeagueRound.LeagueRoundService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LeagueRoundService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllLeagueRoundsByParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SportsDataService.LeagueRound.LeagueRoundService/GetAllLeagueRoundsByParams',
            SportsDataService_dot_LeagueRound_dot_requests__pb2.LeagueRoundsByParamsRequest.SerializeToString,
            SportsDataService_dot_LeagueRound_dot_responses__pb2.LeagueRoundsByParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
