# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SportsDataService/LeagueRound/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSportsDataProtos.SportsDataService.LeagueRound import requests_pb2 as SportsDataService_dot_LeagueRound_dot_requests__pb2
from src.generatedSportsDataProtos.SportsDataService.LeagueRound import responses_pb2 as SportsDataService_dot_LeagueRound_dot_responses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+SportsDataService/LeagueRound/service.proto\x12,SimPitchProtos.SportsDataService.LeagueRound\x1a,SportsDataService/LeagueRound/requests.proto\x1a-SportsDataService/LeagueRound/responses.proto2\xca\x01\n\x12LeagueRoundService\x12\xb3\x01\n\x1aGetAllLeagueRoundsByParams\x12I.SimPitchProtos.SportsDataService.LeagueRound.LeagueRoundsByParamsRequest\x1aJ.SimPitchProtos.SportsDataService.LeagueRound.LeagueRoundsByParamsResponseB/\xaa\x02,SimPitchProtos.SportsDataService.LeagueRoundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SportsDataService.LeagueRound.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002,SimPitchProtos.SportsDataService.LeagueRound'
  _globals['_LEAGUEROUNDSERVICE']._serialized_start=187
  _globals['_LEAGUEROUNDSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
