# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimPitchMl/Predict/requests.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSimPitchMlProtos.SimPitchMl import commonTypes_pb2 as SimPitchMl_dot_commonTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!SimPitchMl/Predict/requests.proto\x12!SimPitchProtos.SimPitchMl.Predict\x1a\x1cSimPitchMl/commonTypes.proto\"I\n\x0ePredictRequest\x12\x37\n\x07predict\x18\x01 \x01(\x0b\x32&.SimPitchProtos.SimPitchMl.PredictGrpcB$\xaa\x02!SimPitchProtos.SimPitchMl.Predictb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimPitchMl.Predict.requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002!SimPitchProtos.SimPitchMl.Predict'
  _globals['_PREDICTREQUEST']._serialized_start=102
  _globals['_PREDICTREQUEST']._serialized_end=175
# @@protoc_insertion_point(module_scope)
