# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.generatedSimPitchMlProtos.SimPitchMl.Predict import requests_pb2 as SimPitchMl_dot_Predict_dot_requests__pb2
from src.generatedSimPitchMlProtos.SimPitchMl.Predict import responses_pb2 as SimPitchMl_dot_Predict_dot_responses__pb2


class PredictServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPrediction = channel.unary_unary(
                '/SimPitchProtos.SimPitchMl.Predict.PredictService/StartPrediction',
                request_serializer=SimPitchMl_dot_Predict_dot_requests__pb2.PredictRequest.SerializeToString,
                response_deserializer=SimPitchMl_dot_Predict_dot_responses__pb2.PredictResponse.FromString,
                )


class PredictServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPrediction,
                    request_deserializer=SimPitchMl_dot_Predict_dot_requests__pb2.PredictRequest.FromString,
                    response_serializer=SimPitchMl_dot_Predict_dot_responses__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimPitchProtos.SimPitchMl.Predict.PredictService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimPitchMl.Predict.PredictService/StartPrediction',
            SimPitchMl_dot_Predict_dot_requests__pb2.PredictRequest.SerializeToString,
            SimPitchMl_dot_Predict_dot_responses__pb2.PredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
