# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SportsDataService/MatchRound/requests.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+SportsDataService/MatchRound/requests.proto\x12+SimPitchProtos.SportsDataService.MatchRound\"/\n\x1bMatchRoundsByRoundIdRequest\x12\x10\n\x08round_id\x18\x01 \x01(\tB.\xaa\x02+SimPitchProtos.SportsDataService.MatchRoundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SportsDataService.MatchRound.requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002+SimPitchProtos.SportsDataService.MatchRound'
  _globals['_MATCHROUNDSBYROUNDIDREQUEST']._serialized_start=92
  _globals['_MATCHROUNDSBYROUNDIDREQUEST']._serialized_end=139
# @@protoc_insertion_point(module_scope)
