# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SportsDataService/MatchRound/responses.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSportsDataProtos.SportsDataService import commonTypes_pb2 as SportsDataService_dot_commonTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,SportsDataService/MatchRound/responses.proto\x12+SimPitchProtos.SportsDataService.MatchRound\x1a#SportsDataService/commonTypes.proto\"f\n\x1cMatchRoundsByRoundIdResponse\x12\x46\n\x0cmatch_rounds\x18\x01 \x03(\x0b\x32\x30.SimPitchProtos.SportsDataService.MatchRoundGrpcB.\xaa\x02+SimPitchProtos.SportsDataService.MatchRoundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SportsDataService.MatchRound.responses_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002+SimPitchProtos.SportsDataService.MatchRound'
  _globals['_MATCHROUNDSBYROUNDIDRESPONSE']._serialized_start=130
  _globals['_MATCHROUNDSBYROUNDIDRESPONSE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
