# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SportsDataService/MatchRound/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from SportsDataService.MatchRound import requests_pb2 as SportsDataService_dot_MatchRound_dot_requests__pb2
from SportsDataService.MatchRound import responses_pb2 as SportsDataService_dot_MatchRound_dot_responses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*SportsDataService/MatchRound/service.proto\x12+SimPitchProtos.SportsDataService.MatchRound\x1a+SportsDataService/MatchRound/requests.proto\x1a,SportsDataService/MatchRound/responses.proto2\xc4\x01\n\x11MatchRoundService\x12\xae\x01\n\x17GetMatchRoundsByRoundId\x12H.SimPitchProtos.SportsDataService.MatchRound.MatchRoundsByRoundIdRequest\x1aI.SimPitchProtos.SportsDataService.MatchRound.MatchRoundsByRoundIdResponseB.\xaa\x02+SimPitchProtos.SportsDataService.MatchRoundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SportsDataService.MatchRound.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002+SimPitchProtos.SportsDataService.MatchRound'
  _globals['_MATCHROUNDSERVICE']._serialized_start=183
  _globals['_MATCHROUNDSERVICE']._serialized_end=379
# @@protoc_insertion_point(module_scope)
