# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.generatedSportsDataProtos.SportsDataService.MatchRound import requests_pb2 as SportsDataService_dot_MatchRound_dot_requests__pb2
from src.generatedSportsDataProtos.SportsDataService.MatchRound import responses_pb2 as SportsDataService_dot_MatchRound_dot_responses__pb2


class MatchRoundServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMatchRoundsByRoundId = channel.unary_unary(
                '/SimPitchProtos.SportsDataService.MatchRound.MatchRoundService/GetMatchRoundsByRoundId',
                request_serializer=SportsDataService_dot_MatchRound_dot_requests__pb2.MatchRoundsByRoundIdRequest.SerializeToString,
                response_deserializer=SportsDataService_dot_MatchRound_dot_responses__pb2.MatchRoundsByRoundIdResponse.FromString,
                )


class MatchRoundServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMatchRoundsByRoundId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchRoundServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMatchRoundsByRoundId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMatchRoundsByRoundId,
                    request_deserializer=SportsDataService_dot_MatchRound_dot_requests__pb2.MatchRoundsByRoundIdRequest.FromString,
                    response_serializer=SportsDataService_dot_MatchRound_dot_responses__pb2.MatchRoundsByRoundIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimPitchProtos.SportsDataService.MatchRound.MatchRoundService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MatchRoundService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMatchRoundsByRoundId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SportsDataService.MatchRound.MatchRoundService/GetMatchRoundsByRoundId',
            SportsDataService_dot_MatchRound_dot_requests__pb2.MatchRoundsByRoundIdRequest.SerializeToString,
            SportsDataService_dot_MatchRound_dot_responses__pb2.MatchRoundsByRoundIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
