from pathlib import Path
from typing import Dict, Optional, Protocol, Union

class JsonFileRepositoryPort(Protocol):
    def get_full_path(self, filename: str) -> Path: ...
    def load(self, filename: str) -> Optional[Union[Dict, list]]: ...
    def save(self, *, filename: str, data: dict) -> None: ...
    def delete(self, filename: str) -> bool: ...