from typing import Dict, Optional, Protocol, Union

class JsonFileRepositoryPort(Protocol):
    def load(self, filename: str) -> Optional[Union[Dict, list]]: ...
    def save(self, *, filename: str, data: dict) -> None: ...