# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimulationService/IterationResult/requests.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSimulationProtos.SimulationService import commonTypes_pb2 as SimulationService_dot_commonTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0SimulationService/IterationResult/requests.proto\x12\x30SimPitchProtos.SimulationService.IterationResult\x1a#SimulationService/commonTypes.proto\"(\n\x1aIterationResultByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x89\x01\n%IterationResultsBySimulationIdRequest\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12I\n\rpaged_request\x18\x02 \x01(\x0b\x32\x32.SimPitchProtos.SimulationService.PagedRequestGrpcB3\xaa\x02\x30SimPitchProtos.SimulationService.IterationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimulationService.IterationResult.requests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0020SimPitchProtos.SimulationService.IterationResult'
  _globals['_ITERATIONRESULTBYIDREQUEST']._serialized_start=139
  _globals['_ITERATIONRESULTBYIDREQUEST']._serialized_end=179
  _globals['_ITERATIONRESULTSBYSIMULATIONIDREQUEST']._serialized_start=182
  _globals['_ITERATIONRESULTSBYSIMULATIONIDREQUEST']._serialized_end=319
# @@protoc_insertion_point(module_scope)
