# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimulationService/IterationResult/responses.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.generatedSimulationProtos.SimulationService import commonTypes_pb2 as SimulationService_dot_commonTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1SimulationService/IterationResult/responses.proto\x12\x30SimPitchProtos.SimulationService.IterationResult\x1a#SimulationService/commonTypes.proto\"n\n\x1bIterationResultByIdResponse\x12O\n\x10iteration_result\x18\x01 \x01(\x0b\x32\x35.SimPitchProtos.SimulationService.IterationResultGrpc\"\xb2\x01\n&IterationResultsBySimulationIdResponse\x12\x44\n\x05items\x18\x01 \x03(\x0b\x32\x35.SimPitchProtos.SimulationService.IterationResultGrpc\x12\x42\n\x05paged\x18\x02 \x01(\x0b\x32\x33.SimPitchProtos.SimulationService.PagedResponseGrpcB3\xaa\x02\x30SimPitchProtos.SimulationService.IterationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimulationService.IterationResult.responses_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\0020SimPitchProtos.SimulationService.IterationResult'
  _globals['_ITERATIONRESULTBYIDRESPONSE']._serialized_start=140
  _globals['_ITERATIONRESULTBYIDRESPONSE']._serialized_end=250
  _globals['_ITERATIONRESULTSBYSIMULATIONIDRESPONSE']._serialized_start=253
  _globals['_ITERATIONRESULTSBYSIMULATIONIDRESPONSE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
