# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.generatedSimulationProtos.SimulationService.IterationResult import requests_pb2 as SimulationService_dot_IterationResult_dot_requests__pb2
from src.generatedSimulationProtos.SimulationService.IterationResult import responses_pb2 as SimulationService_dot_IterationResult_dot_responses__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class IterationResultServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIterationResultById = channel.unary_unary(
                '/SimPitchProtos.SimulationService.IterationResult.IterationResultService/GetIterationResultById',
                request_serializer=SimulationService_dot_IterationResult_dot_requests__pb2.IterationResultByIdRequest.SerializeToString,
                response_deserializer=SimulationService_dot_IterationResult_dot_responses__pb2.IterationResultByIdResponse.FromString,
                )
        self.GetIterationResultsBySimulationId = channel.unary_stream(
                '/SimPitchProtos.SimulationService.IterationResult.IterationResultService/GetIterationResultsBySimulationId',
                request_serializer=SimulationService_dot_IterationResult_dot_requests__pb2.IterationResultsBySimulationIdRequest.SerializeToString,
                response_deserializer=SimulationService_dot_IterationResult_dot_responses__pb2.IterationResultsBySimulationIdResponse.FromString,
                )
        self.SaveIterationResult = channel.unary_unary(
                '/SimPitchProtos.SimulationService.IterationResult.IterationResultService/SaveIterationResult',
                request_serializer=SimulationService_dot_IterationResult_dot_requests__pb2.SaveIterationResultRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class IterationResultServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIterationResultById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIterationResultsBySimulationId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveIterationResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IterationResultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIterationResultById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIterationResultById,
                    request_deserializer=SimulationService_dot_IterationResult_dot_requests__pb2.IterationResultByIdRequest.FromString,
                    response_serializer=SimulationService_dot_IterationResult_dot_responses__pb2.IterationResultByIdResponse.SerializeToString,
            ),
            'GetIterationResultsBySimulationId': grpc.unary_stream_rpc_method_handler(
                    servicer.GetIterationResultsBySimulationId,
                    request_deserializer=SimulationService_dot_IterationResult_dot_requests__pb2.IterationResultsBySimulationIdRequest.FromString,
                    response_serializer=SimulationService_dot_IterationResult_dot_responses__pb2.IterationResultsBySimulationIdResponse.SerializeToString,
            ),
            'SaveIterationResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveIterationResult,
                    request_deserializer=SimulationService_dot_IterationResult_dot_requests__pb2.SaveIterationResultRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimPitchProtos.SimulationService.IterationResult.IterationResultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IterationResultService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIterationResultById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.IterationResult.IterationResultService/GetIterationResultById',
            SimulationService_dot_IterationResult_dot_requests__pb2.IterationResultByIdRequest.SerializeToString,
            SimulationService_dot_IterationResult_dot_responses__pb2.IterationResultByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIterationResultsBySimulationId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SimPitchProtos.SimulationService.IterationResult.IterationResultService/GetIterationResultsBySimulationId',
            SimulationService_dot_IterationResult_dot_requests__pb2.IterationResultsBySimulationIdRequest.SerializeToString,
            SimulationService_dot_IterationResult_dot_responses__pb2.IterationResultsBySimulationIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveIterationResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimPitchProtos.SimulationService.IterationResult.IterationResultService/SaveIterationResult',
            SimulationService_dot_IterationResult_dot_requests__pb2.SaveIterationResultRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
