from typing import List, Optional, Protocol

from src.domain.entities import IterationResult, PredictRequest


class SimulationServicePort(Protocol):
    async def init_prediction(self, predict_request: PredictRequest): ...
    async def run_all_overview_scenario(self): ...
    async def run_get_iterationResults_by_simulationId(self) -> Optional[IterationResult]: ...
    async def get_pending_simulations_to_sync(self) -> List[str]: ...
