from typing import Protocol
class SimulationServicePort(Protocol):
    async def run_all_overview_scenario(self): ...
    async def run_paged_overview_scenario(self): ...
    async def get_pending_simulations_to_sync(self): ...
