from typing import List, Optional, Protocol, Tuple

from src.domain.entities import IterationResult, PredictRequest, TrainingData, TrainingDataset


class SimulationServicePort(Protocol):
    async def run_prediction(self, predict_request: PredictRequest): ...
    async def init_prediction(
        self, predict_request: PredictRequest
) -> TrainingDataset: ...
    async def run_all_overview_scenario(self): ...
    async def run_get_iterationResults_by_simulationId(
        self,
    ) -> Optional[IterationResult]: ...
    async def get_pending_simulations_to_sync(self) -> List[str]: ...
